name: equatable_lint_x_example
description: Package with every examples for the equatable_lint_x package
version: 0.1.0

publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  analyzer: ^5.4.0
  equatable: ^2.0.5

dev_dependencies:
  custom_lint: ^0.2.12
  equatable_lint_x:
    path: ../
