name: equatable_lint_x
version: 0.4.3
description: This is a set of rules to make classes using Equatable more maintainable. We make sure your class use all its fields for comparaison even those of its ancestor if necessary.
homepage: https://github.com/Br0nie5/equatable_lint_x
repository: https://github.com/Br0nie5/equatable_lint_x

environment:
  sdk: ^3.9.0

plugin:
  platforms:
    dart:
      pluginClass: equatable_lint_x
      fileName: main.dart

dependencies:
  analysis_server_plugin: ^0.3.4
  analyzer: ^9.0.0
  analyzer_plugin: ^0.13.11
  collection: ^1.19.1

dev_dependencies:
  analyzer_testing: ^0.1.7
  test: ^1.30.0
  test_reflective_loader: ^0.4.0
