name: Test equatable_lint_x package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  test:
    name: "Test equatable_lint_x"
    runs-on: ubuntu-24.04

    steps:
      # Checkout repository
      - uses: actions/checkout@v6.0.2

      # Setup Dart SDK
      - uses: dart-lang/setup-dart@v1.7.1
        with:
          sdk: 3.10.0

      - name: Install Dependencies
        run: dart pub get

      - name: Analyze
        run: dart analyze lib

      - name: Format
        run: dart format --set-exit-if-changed lib example/lib

      - name: Install lcov
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov

      - name: Test
        run: scripts/test.sh --coverage --ci

      - name: Activate pana pub package to compute package score
        run: dart pub global activate pana

      # It will always need a threshold of 10 since analyser is always
      # ahead of flutter in terms of versions.
      # So we lose points because we are not compatible with the latest
      # versions.
      - name: Check package score
        run: pana --exit-code-threshold=10
